---
- hosts: localhost
  gather_facts: false
  vars:
    job_data_repo: git@github.com:kopecmartin/job-data-repo.git
    job_data_repo_dest: jobs
    job_name: test_job_3
    stestr_path: /home/centos/tempest/.stestr
    job_data_files:
      - times.dbm.bak
      - times.dbm.dat
      - times.dbm.dir
      - format
      - next-stream
  roles:
    - roles/backup
